# Accessible via {{ site.var }}
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Octoscorp
description: >- # this means to ignore newlines until "baseurl:"
  Keeping you informed about all the shenanigans you have no need to care about <3.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  octoscorp

# Build settings
remote_theme: pages-themes/merlot@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

exclude:
  # This one is just for the GitHub, not the page
  - README.md